# Generated by Django 4.2.30 on 2026-04-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('registered_address', models.TextField()),
                ('contact_number', models.CharField(max_length=20)),
                ('contact_person_1', models.CharField(max_length=100)),
                ('contact_person_2', models.CharField(blank=True, default='', max_length=100)),
                ('gst_number', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice Customer',
                'verbose_name_plural': 'Invoice Customers',
                'ordering': ['-created_at'],
            },
        ),
    ]
