# Generated by Django 4.2.30 on 2026-04-29 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_billing_attention_customer_billing_city_and_more'),
        ('invoices', '0002_invoice_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer'),
        ),
    ]
