# Generated by Django 4.2.30 on 2026-05-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_invoice_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='billing_to',
            field=models.TextField(blank=True, default=''),
        ),
    ]
