# Generated by Django 4.2.30 on 2026-05-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_invoice_billing_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='template',
            field=models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('elegant', 'Elegant'), ('minimal', 'Minimal')], default='classic', max_length=20),
        ),
    ]
