# Generated by Django 4.2.30 on 2026-05-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_invoice_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reminder_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
