# Generated by Django 4.2.30 on 2026-04-23 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_invoices', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('on_time_count', models.IntegerField(default=0)),
                ('late_count', models.IntegerField(default=0)),
                ('avg_days_late', models.FloatField(default=0)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('payment_score', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='customers.customer')),
            ],
            options={
                'verbose_name_plural': 'Payment Analytics',
            },
        ),
        migrations.CreateModel(
            name='CreditTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_days', models.IntegerField(choices=[(7, '7 days'), (15, '15 days'), (30, '30 days'), (45, '45 days'), (60, '60 days'), (90, '90 days')])),
                ('reason', models.TextField(blank=True, default='')),
                ('score', models.FloatField(default=0)),
                ('tier', models.CharField(choices=[('PLATINUM', 'Platinum'), ('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze'), ('BLACKLIST', 'Blacklist')], default='BRONZE', max_length=10)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_credits', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_timelines', to='customers.customer')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
    ]
