# Generated by Django 4.2.30 on 2026-04-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentanalytics',
            name='overdue_count',
            field=models.IntegerField(default=0),
        ),
    ]
