# Generated by Django 4.2.30 on 2026-04-24 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice_customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('hsn_code', models.CharField(max_length=20)),
                ('unit', models.CharField(choices=[('Nos', 'Nos'), ('Kg', 'Kg'), ('Ltr', 'Ltr'), ('Mtr', 'Mtr'), ('Box', 'Box'), ('Pcs', 'Pcs'), ('Set', 'Set'), ('Pair', 'Pair'), ('Dozen', 'Dozen'), ('Other', 'Other')], default='Nos', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_percentage', models.IntegerField(choices=[(0, '0%'), (5, '5%'), (12, '12%'), (18, '18%'), (28, '28%')], default=18)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='invoice_customers.invoicecustomer')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'ordering': ['product_name'],
            },
        ),
    ]
