# Generated by Django 4.2.30 on 2026-04-29 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_billing_attention_customer_billing_city_and_more'),
        ('inventory', '0002_inventoryitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='customers.customer'),
        ),
    ]
