# Generated by Django 4.2.30 on 2026-05-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_company_bank_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='company_bank_details',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bank_ifsc',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
